# Generated by Django 5.2.4 on 2025-07-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='userPassword',
            field=models.IntegerField(max_length=100),
        ),
    ]
