# Generated by Django 5.2.4 on 2025-07-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_alter_createuser_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='userPassword',
            field=models.CharField(max_length=100),
        ),
    ]
