# Generated by Django 4.2.28 on 2026-02-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_alter_createuser_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadquestion',
            name='marks',
            field=models.IntegerField(default=10),
        ),
    ]
