# Generated by Django 4.2.28 on 2026-02-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_uploadquestion_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
    ]
