# Generated by Django 4.2.28 on 2026-02-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_createuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='created_at',
            field=models.DateTimeField(default='2026-01-01 00:00:00'),
        ),
    ]
