# Generated by Django 4.2.28 on 2026-02-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_update_created_at_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadquestion',
            name='created_at',
            field=models.DateTimeField(default='2026-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='uploadquestion',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
