# Generated by Django 6.0.2 on 2026-03-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_add_question_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
