# Generated by Django 6.0.2 on 2026-03-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0008_createuser_email'),
    ]

    operations = [
    ]
