# Generated by Django 6.0.2 on 2026-03-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0009_auto_20260329_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='email',
            field=models.EmailField(blank=True, null=True, unique=True),
        ),
    ]
