# Generated by Django 6.0.2 on 2026-04-09 23:40

from django.db import migrations, models
from datetime import datetime, timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0010_auto_20260329_1937'),
    ]

    def set_realistic_dates(apps, schema_editor):
        # Get the models
        createUser = apps.get_model('head', 'createUser')
        uploadQuestion = apps.get_model('head', 'uploadQuestion')
        
        # Set realistic creation dates for users based on their ID
        users = createUser.objects.all().order_by('userId')
        base_date = datetime(2025, 1, 1)  # Start from January 2025
        
        for i, user in enumerate(users):
            # Add days based on user order to simulate different creation times
            created_date = base_date + timedelta(days=i*30)  # 30 days apart
            user.created_at = created_date
            user.save()
        
        # Set realistic dates for questions
        questions = uploadQuestion.objects.all().order_by('id')
        question_base_date = datetime(2025, 6, 1)  # Questions created later
        
        for i, question in enumerate(questions):
            created_date = question_base_date + timedelta(days=i*7)  # 1 week apart
            question.created_at = created_date
            question.save()

    operations = [
        # First update existing data
        migrations.RunPython(set_realistic_dates),
        
        # Then alter the field
        migrations.AlterField(
            model_name='createuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploadquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
