# Generated by Django 5.2.4 on 2025-07-12 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.createuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.uploadquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.createuser')),
            ],
        ),
    ]
