# Generated by Django 5.2.4 on 2025-07-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_interviewresult_interviewsession_studentmarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
