# Generated by Django 4.2.28 on 2026-02-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_useranswer_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
