# Generated by Django 4.2.28 on 2026-02-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentmarks_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='created_at',
            field=models.DateTimeField(default='2026-01-01 00:00:00'),
        ),
    ]
